[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
solana_amm = "Fk852S24kjQ6aqUjEPvX4KUVy77UkQ98f3zvUAnLTZcm"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
